export const PRODUCT_ACTIONS = {
  PRODUCT_INFO: "PRODUCT_INFO_SHOWED",
  PRODUCTS_LIST_INDEX: "PRODUCTS_LIST_INDEX_LISTED",
  PRODUCT_ADD_TO_INDEX_ON_CREATE: "PRODUCT_ADD_TO_INDEX_ON_CREATE",

  // LIST
  LIST_ADD_PRODUCT: "LIST_ADD_PRODUCT",
  LIST_UPDATE_PRODUCTS: "LIST_UPDATE_PRODUCTS",
  LIST_CHANGE_QUANITY: "LIST_CHANGE_QUANITY",
  LIST_REMOVE_PRODUCT: "LIST_REMOVE_PRODUCT",
};
